/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  ReactSidebar: [
    {
      type: 'autogenerated',
      label: 'REact',
      dirName: '.',
      
    },
  ],
  //RutaSidebar: [{type: 'autogenerated', dirName: '.'}],
  // But you can create a sidebar manually
  
  RutaSidebar: [
    {
      type: 'autogenerated',
      label: 'REact',
      dirName: '.',
      items: ['basics/create-a-document'],
    },
  ],
};

export default sidebars;